---
title: "80 - Create data for shiny app"
author: "Jens Linden"
output:
  html_document:
    number_sections: yes
    toc: yes
---

STATUS: Development

# Management summary
Create data to be loaded into shiny app.

# Inits
Initialisations and loading of libraries required:
```{r, warning = FALSE, message = FALSE, results = FALSE}
rm(list=ls())   # clear all
graphics.off()  # close all
Sys.setenv(LANG = "en")
# Libs
# library(checkpoint) # Package management to avoid incompatibilities; not required when dockerized
# checkpoint('2017-10-01') # Use all packages as of date provided
library(data.table) # Efficient and fast data munging in R; just do it
options(datatable.auto.index=FALSE) # Bug fixing for v < 1.9.5
library(ggplot2) # Good quality plots
library(rprojroot) # Rroot folder management
ROOT <- find_root(has_file("PROJECT_ROOT_DIR"))
library(caret) # Classification And REgression Training
source(paste0(ROOT, "/02_code/lib.R"))
options(width = 100)
```

# Load data
```{r}
# Hotel master data
(hot <- readRDS(paste0(ROOT, '/01_data/03_preprocessed/hotels.rds')))
# Analytics base table (ABT) for hotels
(abt_hot <- readRDS(paste0(ROOT, '/01_data/04_results/36_abt_hot_incl_leaders_laggers.rds')))
# Analytics base table (ABT) for reviews
(abt_rev <- readRDS(paste0(ROOT, '/01_data/03_preprocessed/abt_rev.rds')))
# Review data
(rev <- readRDS(paste0(ROOT, '/01_data/03_preprocessed/reviews.rds')))
```

# Prepare hotel data
Combine hotel master data with analyses results and features created.
```{r}
# Inspect
names(hot)
names(abt_hot)
# Define columns to add to hotel data
cols2add <- c("clus", "dist_city_centre", "score_clus_mean", "score_hot_mean", "score_q25", "score_q75", "lead_lag")
# Create result table for hotels
res_hot <- merge(hot,
             abt_hot[, c("id_hot", cols2add), with = F],
             by = "id_hot",
             all = F # Inner join removing NAs
)
# Adding distance to mean for later sorting
res_hot[, score_dist_mean := score_hot_mean - score_clus_mean]
# Sorting data
res_hot <- res_hot[order(score_dist_mean)]
# Removing columns
res_hot$city_lat <- NULL
res_hot$city_lng <- NULL
# Round values
res_hot[, dist_city_centre := round(dist_city_centre)]
# Inspect
res_hot[1:3]
```

# Save data
```{r}
saveRDS(res_hot, paste0(ROOT, '/04_shiny_app/data/80_res_hot.rds'))
```

```{r}

```

